-- =====================================================================
-- Glassmorphism :: Modern UI (v2)
-- =====================================================================
-- A small design system that sits on top of the original Infinity look.
--
-- IDENTITY, in priority order. Keep this order when adding anything:
--   1. Glassmorphism  - translucent frosted panels, layered depth,
--                       hairline highlights, content visible through chrome
--   2. Modern UI       - design tokens, restrained motion, generous spacing
--   3. Phoenix flavour - accent hue, diagonal shear, level/grade tiers
--
-- Phoenix is the *inspiration*, not the target: this is a glassmorphism theme
-- for Project OutFox, not a Phoenix reskin. If a Phoenix cue ever fights the
-- frosted-glass look, the glass wins.
--
-- What lives here:
--   * colour tokens      (palette / accent ramps / glass tint)
--   * motion tokens      (single place to slow down or disable motion)
--   * elevation helpers  (glass cards, hairlines, soft glows, focus rings)
--   * geometry tokens    (the diagonal shear, corner radius)
--
-- Nothing else in the theme has to be touched to retune the look, every
-- switch lives in ModernUI.Config below.
--
-- Style:
--   "aurora"  - new procedural animated background (default, recommended)
--   "video"   - keep the pre-rendered _Background.mp4 background
--   "classic" - fall back to the original Infinity chrome and background
--
-- Palette: phoenix | infinity
-- Accent:  phoenix2 | phoenix | cyan | violet | magenta | lime | amber | ice
-- Motion:  full | reduced | off        (reduced/off help low-end hardware)
-- =====================================================================

ModernUI = {}

ModernUI.Config = {
    Style      = "aurora",
    Palette    = "phoenix",
    Accent     = "phoenix2",
    Motion     = "full",
    Glass      = true,
    Grain      = true,
    Vignette   = true,
    Scanlines  = false,
    GlowBlobs  = 5,
    -- Horizontal shear on chrome: a Phoenix garnish, deliberately subtle so
    -- the frosted glass stays the headline effect. 0 = upright panels.
    Skew       = 0.03,
    -- Corner radius in pixels. Only has an effect when Graphics/Glass is
    -- installed; without that art, quads cannot be rounded at all.
    Radius     = 14,
    -- The diagonal specular streak across glass panels. Purely cosmetic.
    Sheen      = true,
}

-- ---------------------------------------------------------------------
-- Optional art detection
-- ---------------------------------------------------------------------
-- Graphics/Glass is generated by Other/gen_glass_assets.py and is optional.
-- When it is missing, every panel falls back to square-cornered quads, so the
-- theme still runs on a fresh checkout with no assets built.

local function HasGraphic(name)
    local ok, path = pcall(function() return THEME:GetPathG("", name, true) end)
    return ok and path ~= nil and path ~= ""
end

ModernUI.HasGlassArt = HasGraphic("Glass/Corner")
ModernUI.HasShadowArt = HasGraphic("Glass/Shadow")
ModernUI.HasSheenArt = HasGraphic("Glass/Sheen")
ModernUI.HasRingArt = HasGraphic("Glass/Ring")

-- ---------------------------------------------------------------------
-- Tokens
-- ---------------------------------------------------------------------

local AccentRamps = {
    -- Phoenix 2 (2026) is built around an electric green identity.
    phoenix2 = { "#8CFF1F", "#12C98A" },
    -- The original Phoenix generation (2023) leaned on near-white cyan.
    phoenix  = { "#E9FBFF", "#2BA8FF" },
    cyan     = { "#39E6FF", "#3D7BFF" },
    violet   = { "#A177FF", "#5A2BE0" },
    magenta  = { "#FF5FD2", "#7A28FF" },
    lime     = { "#8BFF5A", "#12C9A0" },
    amber    = { "#FFC24A", "#FF5F6D" },
    ice      = { "#DCEBFF", "#6E8CFF" },
}

local Palettes = {
    -- The violet-leaning original modern palette.
    infinity = {
        Base      = "#07070F",
        BaseAlt   = "#120E2E",
        Surface   = "#1A1640",
        SurfaceHi = "#2A2470",
        Glass     = "#231C57",
        Text      = "#F4F6FF",
        TextDim   = "#9AA1CC",
        Hairline  = "1,1,1,0.16",
    },
    -- Phoenix: almost black navy, cooler surfaces, pure white type. Shared by
    -- both Phoenix generations; only the accent hue changes between them.
    phoenix = {
        Base      = "#05070E",
        BaseAlt   = "#0A1224",
        Surface   = "#101B33",
        SurfaceHi = "#1B2E52",
        Glass     = "#16253F",
        Text      = "#FFFFFF",
        TextDim   = "#93A6C4",
        Hairline  = "1,1,1,0.20",
    },
}

-- Status colours are shared by every palette.
ModernUI.Tokens = {
    Good = color("#3BE6A8"),
    Warn = color("#FFC24A"),
    Bad  = color("#FF5470"),
}

-- Swap palettes at runtime. The token table is mutated in place on purpose:
-- other files may already be holding a reference to ModernUI.Tokens, and
-- replacing the table would leave them pointing at the old colours.
function ModernUI.ApplyPalette(name)
    local palette = Palettes[name or ModernUI.Config.Palette] or Palettes.phoenix
    for key, value in pairs(palette) do
        ModernUI.Tokens[key] = color(value)
    end
    return ModernUI.Tokens
end

ModernUI.ApplyPalette()

-- Alpha carried by a colour token, used so helpers can keep the alpha that
-- is baked into the token instead of silently replacing it with 1.
local function ColorAlpha(shade)
    if type(shade) == "table" and type(shade[4]) == "number" then
        return shade[4]
    end
    return 1
end

-- Rebuild a colour token at a given alpha. Gradient edges need this: hard
-- coding raw RGB numbers there would silently ignore the active palette.
local function Tint(shade, alpha)
    if type(shade) ~= "table" then return color("0,0,0," .. tostring(alpha)) end
    return color(string.format("%.4f,%.4f,%.4f,%.4f",
        shade[1] or 0, shade[2] or 0, shade[3] or 0, alpha))
end

ModernUI.Tint = Tint

-- Accent ramp, 1 = bright end, 2 = deep end
function ModernUI.Accent(index)
    local ramp = AccentRamps[ModernUI.Config.Accent] or AccentRamps.phoenix2
    return color(ramp[index or 1])
end

function ModernUI.IsModern()
    return ModernUI.Config.Style ~= "classic"
end

function ModernUI.UseAurora()
    return ModernUI.Config.Style == "aurora"
end

function ModernUI.UseGlass()
    return ModernUI.IsModern() and ModernUI.Config.Glass
end

-- ---------------------------------------------------------------------
-- Geometry
-- ---------------------------------------------------------------------

-- Shared horizontal shear. Classic mode always stays upright.
function ModernUI.Skew()
    if not ModernUI.IsModern() then return 0 end
    return tonumber(ModernUI.Config.Skew) or 0
end

-- Corner radius, clamped so it can never exceed half of the smaller side.
-- Returns 0 when the corner art is missing, which is what makes every caller
-- fall back to plain quads automatically.
function ModernUI.Radius(width, height, requested)
    if not (ModernUI.IsModern() and ModernUI.HasGlassArt) then return 0 end
    local r = tonumber(requested) or tonumber(ModernUI.Config.Radius) or 0
    return math.max(0, math.min(r, math.floor(math.min(width, height) * 0.5)))
end

-- ---------------------------------------------------------------------
-- Motion
-- ---------------------------------------------------------------------

function ModernUI.MotionScale()
    local m = ModernUI.Config.Motion
    if m == "off" then return 0 end
    if m == "reduced" then return 0.55 end
    return 1
end

-- Scale a duration with the current motion setting.
function ModernUI.T(seconds)
    local scale = ModernUI.MotionScale()
    if scale == 0 then return 0.001 end
    return seconds * scale
end

-- Signature easing of the modern layer: snappy in, soft landing.
function ModernUI.EaseIn(actor, seconds)
    local duration = ModernUI.T(seconds or 0.5)
    if duration <= 0.01 then return actor:linear(0.001) end
    return actor:easeoutexpo(duration)
end

function ModernUI.EaseOut(actor, seconds)
    local duration = ModernUI.T(seconds or 0.35)
    if duration <= 0.01 then return actor:linear(0.001) end
    return actor:easeinexpo(duration)
end

-- ---------------------------------------------------------------------
-- Chart level and grade tiers (Phoenix style)
-- ---------------------------------------------------------------------
-- NOTE: the evaluation screen deliberately does NOT use GradeTier. Its grades
-- are official PIU sprite art from Graphics/LetterGrades, chosen by
-- Modules/PIU/Score.GradingEval.lua. Replacing that with generated text would
-- lose the authentic art. Use GradeTier where a grade is rendered as *text*,
-- such as personal bests in the song wheel.

-- Upper bound of each tier -> colour. Tune the numbers here, nothing else.
local LevelTiers = {
    { 4,  "#3BE6A8" },
    { 9,  "#39B6FF" },
    { 14, "#FFD44A" },
    { 18, "#FF9A3C" },
    { 21, "#FF5470" },
    { 24, "#C86BFF" },
}

function ModernUI.LevelColor(level)
    level = tonumber(level) or 0
    for _, tier in ipairs(LevelTiers) do
        if level <= tier[1] then return color(tier[2]) end
    end
    -- Anything above the last tier is the "extreme" bracket.
    return color("#7A28FF")
end

-- The theme's own grade codes, as produced by Modules/PIU/Score.Grading.lua
-- and Score.GradingEval.lua: a "Pass"/"Fail" prefix followed by a code where
-- a leading digit is a repeat count and "P" means "plus". So 3PS is SSS+ and
-- 2A is AA. Mapping them here means grade colours can be driven by the grade
-- the theme actually computed, instead of re-deriving one from a percentage.
local GradeNames = {
    ["3PS"] = "SSS+", ["3S"] = "SSS",
    ["2PS"] = "SS+",  ["2S"] = "SS",
    ["PS"]  = "S+",   ["S"]  = "S",
    ["3PA"] = "AAA+", ["3A"] = "AAA",
    ["2PA"] = "AA+",  ["2A"] = "AA",
    ["PA"]  = "A+",   ["A"]  = "A",
    ["B"]   = "B",    ["C"]  = "C",
    ["D"]   = "D",    ["F"]  = "F",
}

-- Translate a theme grade code into its display name.
-- Returns the name plus whether the run was a fail, because in PIU a failed
-- run is a fail no matter how good the letter looks.
function ModernUI.GradeName(grade)
    grade = tostring(grade or "F")
    local failed = grade:sub(1, 4) == "Fail"
    local code = grade:gsub("^Pass", ""):gsub("^Fail", "")
    return GradeNames[code] or code, failed
end

-- Minimum percentage -> grade name, highest first.
-- These mirror the score cutoffs in Modules/PIU/Score.Grading.lua (which works
-- in points out of 1000000) divided by 10000. Keep the two in sync: if they
-- drift, the same play gets one grade on the score plate and a different one
-- anywhere GradeTier is used.
local GradeTiers = {
    { 99.5, "SSS+" }, { 99,   "SSS" },
    { 98.5, "SS+"  }, { 98,   "SS"  },
    { 97.5, "S+"   }, { 97,   "S"   },
    { 96,   "AAA+" }, { 95,   "AAA" },
    { 92.5, "AA+"  }, { 90,   "AA"  },
    { 82.5, "A+"   }, { 75,   "A"   },
    { 65,   "B"    }, { 55,   "C"   },
    { 45,   "D"    },
}

-- Accepts either a 0-1 ratio (what the engine usually hands out) or an
-- already-scaled 0-100 percentage.
-- Prefer GradeName() when the theme has already computed a grade: this is a
-- derivation, that is the real thing.
function ModernUI.GradeTier(percent)
    percent = tonumber(percent) or 0
    if percent > 0 and percent <= 1 then percent = percent * 100 end

    for _, tier in ipairs(GradeTiers) do
        if percent >= tier[1] then return tier[2] end
    end
    return "F"
end

-- Colour for a grade. Accepts either a theme grade code ("Pass3PS") or a
-- display name ("SSS+").
function ModernUI.GradeColor(grade)
    local name, failed = ModernUI.GradeName(grade)
    if failed then return ModernUI.Tokens.Bad end

    local head = name:sub(1, 1)
    if head == "S" then return ModernUI.Accent(1) end
    if head == "A" then return ModernUI.Tokens.Good end
    if name == "F" then return ModernUI.Tokens.Bad end
    return ModernUI.Tokens.Warn
end

-- ---------------------------------------------------------------------
-- Elevation helpers
-- ---------------------------------------------------------------------

-- A 1px bright line used to separate surfaces, the cheapest way to make
-- flat panels read as layered glass.
function ModernUI.Hairline(params)
    params = params or {}
    local width = params.w or 200
    local thickness = params.thickness or 1
    local shade = params.color or ModernUI.Tokens.Hairline
    local skew = params.skew or 0
    -- diffusealpha() replaces the alpha carried by the colour token, so the
    -- token's own alpha is the default here. Callers that want a brighter
    -- line (the glass card highlight, for example) still pass params.alpha.
    local alpha = params.alpha or ColorAlpha(shade)

    return Def.Quad {
        InitCommand = function(self)
            self:xy(params.x or 0, params.y or 0)
                :zoomto(width, thickness)
                :halign(params.halign or 0.5):valign(params.valign or 0.5)
                :skewx(skew)
                :diffuse(shade):diffusealpha(alpha)
        end
    }
end

-- Additive radial glow built from the texture the theme already ships.
function ModernUI.SoftGlow(params)
    params = params or {}
    local shade = params.color or ModernUI.Accent(1)
    local baseZoom = params.zoom or 1

    return Def.Sprite {
        Texture = THEME:GetPathG("", "Background/circle"),
        InitCommand = function(self)
            self:xy(params.x or 0, params.y or 0)
                :zoom(baseZoom)
                :blend("BlendMode_Add")
                :diffuse(shade)
                :diffusealpha(params.alpha or 0.2)

            if params.pulse and ModernUI.MotionScale() > 0 then
                -- pulse() drives zoom directly, so the magnitude has to be
                -- expressed in absolute zoom. Feeding it a bare 1 -> 1.06
                -- would throw away baseZoom and snap the glow down to 1x.
                -- params.pulse may be `true` (default ratio) or a number
                -- describing how far the glow should breathe.
                local ratio = tonumber(params.pulse) or 1.06
                self:pulse()
                    :effectmagnitude(baseZoom, baseZoom * ratio, 1)
                    :effectperiod(ModernUI.T(params.period or 4))
                    :effectoffset(params.offset or 0)
            end
        end
    }
end

-- Thin rounded outline, for avatar frames and focus states.
-- Caveat: Ring.png is a square texture, so stretching it to a strongly
-- non-square size distorts the corner radius. Use it where w and h are close.
function ModernUI.FocusRing(params)
    params = params or {}
    if not ModernUI.HasRingArt then return Def.Actor {} end

    return Def.Sprite {
        Texture = THEME:GetPathG("", "Glass/Ring"),
        InitCommand = function(self)
            self:xy(params.x or 0, params.y or 0)
                :zoomto(params.w or 96, params.h or 96)
                :halign(params.halign or 0.5):valign(params.valign or 0.5)
                :diffuse(params.color or ModernUI.Accent(1))
                :diffusealpha(params.alpha or 0.9)
        end
    }
end

-- Frosted panel: shadow -> translucent gradient body -> top highlight ->
-- optional sheen -> accent bar. This is the core of the theme's identity, so
-- keep it reading as *glass*: the body must stay translucent and tinted from
-- the palette, never an opaque plate.
--
-- Geometry is a nine-slice when Graphics/Glass is installed: straight edges
-- are quads, and the four corners are one rounded-corner sprite drawn four
-- times at 0/90/180/270 degrees. Without that art the radius resolves to 0 and
-- the panel is a single quad, exactly as before.
--
-- The shear is applied to the card's own ActorFrame rather than to each piece.
-- Skewing the slices individually would shift them by different amounts and
-- tear the corners away from the edges.
function ModernUI.GlassCard(params)
    params = params or {}
    local width  = params.w or 320
    local height = params.h or 120
    local halign = params.halign or 0.5
    local valign = params.valign or 0.5
    local alpha  = params.alpha or 0.55
    local accent = params.accent or ModernUI.Accent(1)
    local accentBar = params.accentBar ~= false
    local skew = params.skew or ModernUI.Skew()
    local radius = ModernUI.Radius(width, height, params.radius)

    -- Panel bounds relative to the frame's origin.
    local left, top = -halign * width, -valign * height
    local right, bottom = left + width, top + height

    local topShade = Tint(ModernUI.Tokens.SurfaceHi, alpha)
    local bottomShade = Tint(ModernUI.Tokens.Base, math.min(alpha + 0.2, 1))

    local card = Def.ActorFrame {
        InitCommand = function(self)
            self:xy(params.x or 0, params.y or 0):skewx(skew)
        end
    }

    -- Ambient shadow. The pre-blurred sprite is much softer than a quad, but a
    -- quad is a fine stand-in when the art is absent.
    if ModernUI.HasShadowArt then
        card[#card + 1] = Def.Sprite {
            Texture = THEME:GetPathG("", "Glass/Shadow"),
            InitCommand = function(self)
                self:zoomto(width + 40, height + 40)
                    :halign(halign):valign(valign)
                    :diffuse(color("#000008")):diffusealpha(0.45 * alpha)
            end
        }
    else
        card[#card + 1] = Def.Quad {
            InitCommand = function(self)
                self:zoomto(width + 12, height + 12)
                    :halign(halign):valign(valign)
                    :diffuse(color("#000008")):diffusealpha(0.32 * alpha)
            end
        }
    end

    if radius > 0 then
        -- Middle band: full width, carries the vertical gradient.
        card[#card + 1] = Def.Quad {
            InitCommand = function(self)
                self:zoomto(width, height - radius * 2)
                    :halign(0.5):valign(0.5)
                    :x((left + right) * 0.5):y((top + bottom) * 0.5)
                    :diffuse(ModernUI.Tokens.Glass or ModernUI.Tokens.Surface)
                    :diffusetopedge(Tint(ModernUI.Tokens.SurfaceHi, alpha))
                    :diffusebottomedge(bottomShade)
            end
        }

        -- Top and bottom bands, inset by the radius so they stop where the
        -- corner sprites begin.
        for _, band in ipairs({
            { y = top, valign = 0, shade = topShade },
            { y = bottom, valign = 1, shade = bottomShade },
        }) do
            card[#card + 1] = Def.Quad {
                InitCommand = function(self)
                    self:zoomto(width - radius * 2, radius)
                        :halign(0.5):valign(band.valign)
                        :x((left + right) * 0.5):y(band.y)
                        :diffuse(band.shade)
                end
            }
        end

        -- Four corners from one texture. Rotation is clockwise, and the source
        -- tile is the top-left corner, so 0/90/180/270 walks around the panel.
        for _, spot in ipairs({
            { x = left + radius * 0.5,  y = top + radius * 0.5,    rot = 0,   shade = topShade },
            { x = right - radius * 0.5, y = top + radius * 0.5,    rot = 90,  shade = topShade },
            { x = right - radius * 0.5, y = bottom - radius * 0.5, rot = 180, shade = bottomShade },
            { x = left + radius * 0.5,  y = bottom - radius * 0.5, rot = 270, shade = bottomShade },
        }) do
            card[#card + 1] = Def.Sprite {
                Texture = THEME:GetPathG("", "Glass/Corner"),
                InitCommand = function(self)
                    self:xy(spot.x, spot.y)
                        :zoomto(radius, radius)
                        :rotationz(spot.rot)
                        :diffuse(spot.shade)
                end
            }
        end
    else
        -- No corner art: one quad, square corners, same gradient.
        card[#card + 1] = Def.Quad {
            InitCommand = function(self)
                self:zoomto(width, height)
                    :halign(halign):valign(valign)
                    :diffuse(ModernUI.Tokens.Glass or ModernUI.Tokens.Surface)
                    :diffusetopedge(Tint(ModernUI.Tokens.SurfaceHi, alpha))
                    :diffusebottomedge(bottomShade)
            end
        }
    end

    -- Diagonal specular streak. Additive and very faint, so the slight overhang
    -- past a rounded corner is not noticeable.
    if ModernUI.HasSheenArt and ModernUI.Config.Sheen and params.sheen ~= false then
        card[#card + 1] = Def.Sprite {
            Texture = THEME:GetPathG("", "Glass/Sheen"),
            InitCommand = function(self)
                self:zoomto(width, height)
                    :halign(halign):valign(valign)
                    :blend("BlendMode_Add")
                    :diffuse(ModernUI.Tokens.Text)
                    :diffusealpha(params.sheenAlpha or 0.10)
            end
        }
    end

    -- Top highlight hairline, inset so it does not poke out of the corners.
    card[#card + 1] = ModernUI.Hairline {
        w = width - radius * 2, thickness = 1,
        x = (left + right) * 0.5,
        y = top,
        alpha = 0.9,
    }

    -- Accent bar, the single strongest "this is new" signal
    if accentBar then
        card[#card + 1] = Def.Quad {
            InitCommand = function(self)
                self:zoomto(width - radius * 2, params.accentThickness or 3)
                    :halign(0.5):valign(0)
                    :x((left + right) * 0.5)
                    :y(top)
                    :diffuse(accent)
                    :diffuserightedge(ModernUI.Accent(2))
                    :blend("BlendMode_Add")
                    :diffusealpha(0.85)
            end
        }
    end

    return card
end

-- Convenience wrapper so BGAnimations can build a full-width chrome bar.
function ModernUI.ChromeBar(params)
    params = params or {}
    local height = params.h or 84
    local skew = params.skew or ModernUI.Skew()
    -- A sheared quad pulls its top and bottom edges sideways, which would
    -- expose a wedge of background at the screen edges. Grow the bar by the
    -- offset the shear introduces so it always bleeds off-screen.
    local bleed = math.abs(skew) * height * 2 + 8

    return ModernUI.GlassCard {
        x = params.x or SCREEN_CENTER_X,
        y = params.y or 0,
        w = params.w or (SCREEN_WIDTH + bleed),
        h = height,
        halign = 0.5,
        valign = params.valign or 0,
        alpha = params.alpha or 0.6,
        accentBar = params.accentBar ~= false,
        accentThickness = params.accentThickness or 2,
        skew = skew,
        -- A bar that bleeds off both screen edges must not round those edges.
        radius = params.radius or 0,
    }
end

Trace("[Glassmorphism] Modern UI v2 loaded (style: " .. tostring(ModernUI.Config.Style)
    .. ", palette: " .. tostring(ModernUI.Config.Palette)
    .. ", accent: " .. tostring(ModernUI.Config.Accent)
    .. ", motion: " .. tostring(ModernUI.Config.Motion)
    .. ", glass art: " .. tostring(ModernUI.HasGlassArt) .. ")")
